### ISSUE TITLE
Repo Available?

### ISSUE THREAD

**Issue by mjallday** [Yleisradio/aws-maven#5]
![image](https://cloud.githubusercontent.com/assets/252280/14361524/19af40da-fcb0-11e5-8c34-1d54919a5366.png)

I followed the instructions for adding the repo and extension but it does not appear to work

```
[INFO] Scanning for projects...
[WARNING] The POM for fi.yle.tools:aws-maven:jar:1.3.0 is missing, no dependency information available
```

Any ideas?

**Comment by huima** [comment]
Try version 1.4.0.

Need to fix docs.

**Comment by huima** [comment]
http://maven.c4.yle.fi/release/fi/yle/tools/aws-maven/1.4.0/aws-maven-1.4.0.pom

**Comment by huima** [comment]
Fixed documentation to show correct version. Apologies for our mistake.
